[tox]
envlist = py39, py310, py311, py312, py313, flake8
requires = tox-uv>=1.0.0

[testenv]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pytest --basetemp={envtmpdir}

[testenv:flake8]
runner = uv-venv-runner
deps = flake8
commands = flake8 auth_service tests
