"""empty message

Revision ID: b35356fe66ab
Revises: 492259ae8492
Create Date: 2021-01-28 18:33:45.826325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35356fe66ab'
down_revision = '492259ae8492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'full_name')
    # ### end Alembic commands ###
