"""empty message

Revision ID: cc7801029076
Revises: b7374d0bee0f
Create Date: 2021-02-19 21:06:49.633451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7801029076'
down_revision = 'b7374d0bee0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=100), server_default='', nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(length=1), server_default='', nullable=False))
    op.add_column('users', sa.Column('language', sa.String(length=100), server_default='', nullable=False))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('users', 'language')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
